### ISSUE TITLE
Error with Pop Up when starting new Game

### ISSUE THREAD

**Issue by Hattexmc111** [WLahn/VierGewinnt#2]
When game is completed, new game msg-Box appears.
When clicking yes, it does not disapear -> But it should
When clicking no, you can resume playing on the old (already finished) board -> should close?

**Comment by WLahn** [comment]
Fixed in d38ecbbe064906ed1c813bf34fd2b22e9fc7ace2

Model.ResetField() did not reset 'Winner' and 'Finished'
