### ISSUE TITLE
Difficulty Selector

### ISSUE THREAD

**Issue by Hattexmc111** [WLahn/VierGewinnt#4]
Suggestion: Adding difficulty selector: moderate -> hard (at the moment according to minmax depth 3 -> 5)
If someone can beat the KI at 5, this person could test with depth 7 to find out if this is an improvement of difficulty or unneccessary calculation

**Comment by WLahn** [comment]
Merged in f69ec69a220e590d8bd89745fdc9c98bd2d7bd22
